# Generated by Django 4.2 on 2024-09-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="clients",
            field=models.ManyToManyField(
                blank=True,
                related_name="clients",
                to="mail.client",
                verbose_name="Клиенты",
            ),
        ),
    ]
